spring.application.name=medistore

# Server port
server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=${DB_URL}?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=86400000
app.jwt.refresh-expiration=7

# Reset password
app.reset-token.expiration=300

# Email to reset password
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend link for password reset
app.reset-password.url=http://localhost:3000/reset-password?token=
# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# AI chat
openrouter.api.key=${OPENROUTER_API_KEY}
openrouter.model=nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free
# =========================
# VNPAY
# =========================
vnpay.tmn-code=41XI49LI
vnpay.hash-secret=LW5IFKFBN9PEOT51BK4YR56TQ1LQ0CA1

vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

# frontend nhận kết quả
vnpay.return-url=http://localhost:8080/api/payments/vnpay-return

# backend nhận IPN
vnpay.ipn-url=https://medistore-backend-i0de.onrender.com/api/payments/vnpay-ipn

# =========================
# ZALOPAY
# =========================
zalopay.app-id=554
zalopay.key1=8NdU5pG5R2spGHGhyO99HN1OhD8IQJBn
zalopay.key2=uUfsWgfLkRLzq6W2uNXTCxrfxs51auny

zalopay.create-order-url=https://sb-openapi.zalopay.vn/v2/create
zalopay.query-order-url=https://sb-openapi.zalopay.vn/v2/query
